name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
          node-version: '18'

      - name: Install
        run: yarn install

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd packages/core
          yarn build
          npm publish --access public
